
"""
This template is intended for creating simple validators.

If your validator is complex or requires additional post-installation steps, consider using the template repository instead.

The template repository can be found here: https://github.com/guardrails-ai/validator-template
"""
import re

from typing import Any, Callable, Dict, Optional, List

from guardrails.validator_base import (
    ErrorSpan,
    FailResult,
    PassResult,
    ValidationResult,
    Validator,
    register_validator,
)

@register_validator(name="guardrails/internal_domains", data_type="string")
class InternalDomains(Validator):
    """# Overview

    | Developed by | David Tam |
    | Date of development | Aug 13, 2024 |
    | Validator type | Format |
    | License | Apache 2 |
    | Input/Output | Output |

    # Description
    Identifies internal domains in a string output.
    
    ## (Optional) Intended Use
    finds internal domains in a string output like "internal.example.com" or "example.internal".

    ## Requirements

    * Dependencies:
        - guardrails-ai>=0.4.0

    * Dev Dependencies:
        - pytest
        - pyright
        - ruff

    # Installation

    ```bash
    $ guardrails hub install hub://guardrails/internal_domains
    ```

    # Usage Examples

    ## Validating string output via Python

    In this example, we apply the validator to a string output generated by an LLM.

    ```python
    # Import Guard and Validator
    from guardrails.hub import InternalDomains
    from guardrails import Guard

    # Setup Guard
    guard = Guard.use(
        InternalDomains(internal_domains= ["internal.example.com"]),
    )

    guard.validate("This is a string with no domains except a reference to https://www.example.com")  # Validator passes
    guard.validate("This string includes a link to https://internal.example.com/wiki/welcome-guide")  # Validator fails
    ```
    """  # noqa
    def __init__(self, internal_domains: List[str], on_fail: Optional[Callable] = None):
        super().__init__(on_fail=on_fail, internal_domains=internal_domains)
        self.internal_domains = internal_domains

    def _validate(self, value: str, metadata: Dict) -> ValidationResult:
        mentioned_domains = []
        error_spans = []

        # find uris in value
        # Regex pattern to match URIs for the specified domain or domain alone
        for domain in self.internal_domains:
            pattern = rf"https?://(?:\w+\.)*{re.escape(domain)}(?:/[\w\-/]*)?|{re.escape(domain)}(?:/[\w\-/]*)?"
            # Find all matches
             # Find all matches
            for match in re.finditer(pattern, value):
                mentioned_domains.append(match.group())
                span_start = match.start()
                span_end = match.end()
                error_spans.append(ErrorSpan(
                    start=span_start, 
                    end=span_end, 
                    reason=f"Internal domain detected in {span_start}:{span_end}",))

        if len(mentioned_domains) > 0:
            on_fix = value
            for domain in mentioned_domains:
                # Filter out the mentioned_domains
                on_fix = on_fix.replace(domain, f"{'*' * len(domain)}")
            return FailResult(
                error_message=f"Found internal domains: {', '.join(mentioned_domains)}",
                fix_value=on_fix,
                error_spans=error_spans,
            )
        else:
            return PassResult()

# Run tests via `pytest -rP ./internal_domains.py`
class TestInternalDomains:
    def test_success_case(self):
        pass_input = """
        This is a string with no domains except a reference to https://www.example.com  
        """
        validator = InternalDomains(internal_domains=["internal.company.com"])
        result = validator.validate(pass_input, {})
        assert isinstance(result, PassResult) is True

    def test_failure_case(self):
        fail_input = """
This is a comprehensive resource for articles and information related to our company policies and procedures. 
You can access it [here](https://kb.internal.company.com/api/v1/articles). You can learn more about projects [here](https://project-x.company.com/api/v1/articles).
"""
        validator = InternalDomains(internal_domains=["internal.company.com", "project-x.company.com"])
        result = validator.validate(fail_input, {})
        assert isinstance(result, FailResult) is True
        assert result.error_message == "Found internal domains: https://kb.internal.company.com/api/v1/articles, https://project-x.company.com/api/v1/articles"
        assert result.fix_value == """
This is a comprehensive resource for articles and information related to our company policies and procedures. 
You can access it [here](***********************************************). You can learn more about projects [here](*********************************************).
"""
